default_platform(:android)

platform :android do
  desc "Submit a new Debug Build"
  lane :internal do
    gradle(task: 'bundle', build_type: "Release")
    upload_to_play_store(
      track: 'internal',
      version_name: "Ikeji",
      version_code: 2,
      release_status: "draft",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      version_name: "Ikeji",
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_changelogs: true
    )
  end
end
